plugins {
    id 'java'
    id 'application'
}

application {
    mainClass.set("org/example/BankRateTest") // this is working. command in git bash ./gradlew run
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation("org.seleniumhq.selenium:selenium-java:4.34.0")
}

task {

}

test {
    useJUnitPlatform()
}

